--------------------------------------------------------
--  File created - sobota-kwietnia-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ID_KONSUMENTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INZYNIERKA"."ID_KONSUMENTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_MARKI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INZYNIERKA"."ID_MARKI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_PRODUCENTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INZYNIERKA"."ID_PRODUCENTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ID_RODZ_MARKETINGU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INZYNIERKA"."ID_RODZ_MARKETINGU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LICZNIK_RUND_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INZYNIERKA"."LICZNIK_RUND_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BADANIA_RYNKU
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."BADANIA_RYNKU" 
   (	"PRODUCENT_ID_PRODUCENTA" NUMBER(3,0), 
	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"LICZBA_KLIENTOW" NUMBER(10,0), 
	"HORYZONT_CZASOWY" NUMBER(5,0), 
	"DOKLADNOSC" NUMBER(6,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIA_CEN
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."HISTORIA_CEN" 
   (	"CENA" NUMBER(5,0), 
	"MARKA_ID_MARKI" NUMBER(6,0), 
	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KONSUMENT
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."KONSUMENT" 
   (	"ID_KONSUMENTA" NUMBER(10,0), 
	"CENA_POZIOM_ASPIRACJI" NUMBER(5,0), 
	"CENA_POZIOM_REZERWACJI" NUMBER(5,0), 
	"CENA_NIEZADOWOLENIE" NUMBER(4,2), 
	"CENA_ZADOWOLENIE" NUMBER(4,2), 
	"JAKOSC_POZIOM_ASPIRACJI" NUMBER(2,0), 
	"JAKOSC_POZIOM_REZERWACJI" NUMBER(2,0), 
	"JAKOSC_NIEZADOWOLENIE" NUMBER(4,2), 
	"JAKOSC_ZADOWOLENIE" NUMBER(4,2), 
	"PRZYWIAZANIE_POZIOM_ASPIRACJI" NUMBER(4,2), 
	"PRZYWIAZANIE_POZIOM_REZERWACJI" NUMBER(4,2), 
	"PRZYWIAZANIE_NIEZADOWOLENIE" NUMBER(4,2), 
	"PRZYWIAZANIE_ZADOWOLENIE" NUMBER(4,2), 
	"PODATNOSC_NA_MARKETING" NUMBER(2,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KOSZT_MAGAZYNOWANIA
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."KOSZT_MAGAZYNOWANIA" 
   (	"NR_PRZEDZIALU" NUMBER(3,0), 
	"KOSZT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LICZNIK_RUND
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."LICZNIK_RUND" 
   (	"NUMER_RUNDY" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAGAZYNOWANIE
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."MAGAZYNOWANIE" 
   (	"ILOSC" NUMBER(8,0), 
	"KOSZT" NUMBER(10,0), 
	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARKA
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."MARKA" 
   (	"ID_MARKI" NUMBER(6,0), 
	"CENA_ZA_SZTUKE" NUMBER(5,0), 
	"PRODUCENT_ID_PRODUCENTA" NUMBER(3,0), 
	"RODZAJE_MAREK_JAKOSC_MARKI" NUMBER(2,0), 
	"NAZWA" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARKETING
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."MARKETING" 
   (	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"RODZ_MARKET_ID_RODZ_MARKETINGU" NUMBER(2,0), 
	"LICZBA_KLIENTOW" NUMBER(10,0), 
	"KOSZT" NUMBER(10,0), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCENT
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."PRODUCENT" 
   (	"ID_PRODUCENTA" NUMBER(3,0), 
	"NAZWA" VARCHAR2(50 CHAR), 
	"FUNDUSZE" NUMBER(10,0), 
	"CZY_SPASOWAL" CHAR(1 CHAR) DEFAULT 'n'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "INZYNIERKA"."PRODUCENT"."CZY_SPASOWAL" IS '''n'' - NIE
''t'' - TAK';
--------------------------------------------------------
--  DDL for Table PRODUKCJA
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."PRODUKCJA" 
   (	"ILOSC" NUMBER(10,0), 
	"KOSZT" NUMBER(10,0), 
	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRZYWIAZANIE_DO_MARKI
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" 
   (	"KONSUMENT_ID_KONSUMENTA" NUMBER(10,0), 
	"WSPOLCZYNNIK_PRZYWIAZANIA" NUMBER(4,2), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RODZAJE_MAREK
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."RODZAJE_MAREK" 
   (	"JAKOSC_MARKI" NUMBER(2,0), 
	"KOSZT_UTWORZENIA" NUMBER(5,0), 
	"KOSZT_PRODUKCJI_SZTUKI" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RODZAJ_MARKETINGU
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."RODZAJ_MARKETINGU" 
   (	"ID_RODZAJU_MARKETINGU" NUMBER(2,0), 
	"KOSZT_STALY" NUMBER(5,0), 
	"KOSZTA_PER_KLIENT" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPRZEDAZ
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."SPRZEDAZ" 
   (	"ILOSC" NUMBER(10,0), 
	"PRZYCHOD" NUMBER(10,0), 
	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USTAWIENIA_POCZATKOWE
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" 
   (	"NUMER_OPCJI" NUMBER, 
	"LICZBA_KONSUMENTOW" NUMBER(10,0), 
	"WARUNEK_ZAKONCZENIA_RUNDY" CHAR(1 CHAR), 
	"CZAS_RUNDY" NUMBER(4,0), 
	"LICZBA_RUND" NUMBER(5,0), 
	"POCZATKOWE_FUNDUSZE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "INZYNIERKA"."USTAWIENIA_POCZATKOWE"."WARUNEK_ZAKONCZENIA_RUNDY" IS '''t'' - up³yn¹³ okreœlony czas
''m'' - wszyscy gracz wykonali ruch
''b'' - up³yn¹³ okreœlony czas lub wszyscy gracze wykonali ruch ';
   COMMENT ON COLUMN "INZYNIERKA"."USTAWIENIA_POCZATKOWE"."CZAS_RUNDY" IS 'Czas w godzinach. Jeœli jest wybrana opcja, w której warunkiem zakoñczenia rundy jest ruch wszystkich graczy, wówczas czas nie jest brany pod uwagê.';
--------------------------------------------------------
--  DDL for Table ZAKUP_KONSUMENTA
--------------------------------------------------------

  CREATE TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" 
   (	"LICZNIK_RUND_NUMER_RUNDY" NUMBER(5,0), 
	"KONSUMENT_ID_KONSUMENTA" NUMBER(10,0), 
	"MARKA_ID_MARKI" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INZYNIERKA.BADANIA_RYNKU
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.HISTORIA_CEN
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.KONSUMENT
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.KOSZT_MAGAZYNOWANIA
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.LICZNIK_RUND
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.MAGAZYNOWANIE
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.MARKA
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.MARKETING
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.PRODUCENT
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.PRODUKCJA
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.PRZYWIAZANIE_DO_MARKI
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.RODZAJE_MAREK
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.RODZAJ_MARKETINGU
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.SPRZEDAZ
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.USTAWIENIA_POCZATKOWE
SET DEFINE OFF;
REM INSERTING into INZYNIERKA.ZAKUP_KONSUMENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HISTORIA_CEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."HISTORIA_CEN_PK" ON "INZYNIERKA"."HISTORIA_CEN" ("MARKA_ID_MARKI", "LICZNIK_RUND_NUMER_RUNDY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RODZAJE_MAREK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."RODZAJE_MAREK_PK" ON "INZYNIERKA"."RODZAJE_MAREK" ("JAKOSC_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAGAZYNOWANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."MAGAZYNOWANIE_PK" ON "INZYNIERKA"."MAGAZYNOWANIE" ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USTAWIENIA_POCZATKOWE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."USTAWIENIA_POCZATKOWE_PK" ON "INZYNIERKA"."USTAWIENIA_POCZATKOWE" ("NUMER_OPCJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRZYWIAZANIE_DO_MARKI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI_PK" ON "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" ("KONSUMENT_ID_KONSUMENTA", "MARKA_ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."PRODUCENT_PK" ON "INZYNIERKA"."PRODUCENT" ("ID_PRODUCENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPRZEDAZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."SPRZEDAZ_PK" ON "INZYNIERKA"."SPRZEDAZ" ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KOSZT_MAGAZYNOWANIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."KOSZT_MAGAZYNOWANIA_PK" ON "INZYNIERKA"."KOSZT_MAGAZYNOWANIA" ("NR_PRZEDZIALU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MARKA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."MARKA_PK" ON "INZYNIERKA"."MARKA" ("ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ZAKUP_KONSUMENTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."ZAKUP_KONSUMENTA_PK" ON "INZYNIERKA"."ZAKUP_KONSUMENTA" ("KONSUMENT_ID_KONSUMENTA", "LICZNIK_RUND_NUMER_RUNDY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MARKA_NAZWA_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."MARKA_NAZWA_UN" ON "INZYNIERKA"."MARKA" ("NAZWA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BADANIA_RYNKU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."BADANIA_RYNKU_PK" ON "INZYNIERKA"."BADANIA_RYNKU" ("PRODUCENT_ID_PRODUCENTA", "LICZNIK_RUND_NUMER_RUNDY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MARKETING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."MARKETING_PK" ON "INZYNIERKA"."MARKETING" ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LICZNIK_RUND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."LICZNIK_RUND_PK" ON "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KONSUMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."KONSUMENT_PK" ON "INZYNIERKA"."KONSUMENT" ("ID_KONSUMENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RODZAJ_MARKETINGU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."RODZAJ_MARKETINGU_PK" ON "INZYNIERKA"."RODZAJ_MARKETINGU" ("ID_RODZAJU_MARKETINGU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUKCJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INZYNIERKA"."PRODUKCJA_PK" ON "INZYNIERKA"."PRODUKCJA" ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FKNTM_MARKA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."FKNTM_MARKA" BEFORE
    UPDATE OF producent_id_producenta, rodzaje_marek_jakosc_marki ON marka
    FOR EACH ROW
BEGIN
    IF :NEW.producent_id_producenta <> :OLD.producent_id_producenta OR :NEW.rodzaje_marek_jakosc_marki <> :OLD.rodzaje_marek_jakosc_marki
    THEN
        raise_application_error(-20225, 'Non Transferable FK constraint  on table MARKI is violated');
    END IF;
END;

/
ALTER TRIGGER "INZYNIERKA"."FKNTM_MARKA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FKNTM_ZAKUP_KONSUMENTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."FKNTM_ZAKUP_KONSUMENTA" BEFORE
    UPDATE OF konsument_id_konsumenta ON zakup_konsumenta
BEGIN
    raise_application_error(-20225, 'Non Transferable FK constraint  on table ZAKUP_KONSUMENTA is violated');
END;

/
ALTER TRIGGER "INZYNIERKA"."FKNTM_ZAKUP_KONSUMENTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_KONSUMENTA_AUTOINC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."ID_KONSUMENTA_AUTOINC" 
BEFORE INSERT ON KONSUMENT
FOR EACH ROW
BEGIN
    SELECT ID_KONSUMENTA_SEQ.NEXTVAL
    INTO :NEW.ID_KONSUMENTA
    FROM DUAL;
END;

/
ALTER TRIGGER "INZYNIERKA"."ID_KONSUMENTA_AUTOINC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_PRODUCENTA_AUTOINC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."ID_PRODUCENTA_AUTOINC" 
--wyzwalacz odpowiedzielny za przydzial producentowi unikatowego identyfikatora oraz funduszy o wielkosci okreslonej w ustawieniach poczatkowych
BEFORE INSERT ON PRODUCENT
FOR EACH ROW
BEGIN
    SELECT ID_PRODUCENTA_SEQ.NEXTVAL
    INTO :NEW.ID_PRODUCENTA
    FROM DUAL;

    select poczatkowe_fundusze into :NEW.fundusze from ustawienia_poczatkowe where numer_opcji = 1;
END;

/
ALTER TRIGGER "INZYNIERKA"."ID_PRODUCENTA_AUTOINC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KOSZT_UTWORZENIA_MARKI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."KOSZT_UTWORZENIA_MARKI" 
AFTER INSERT ON MARKA
FOR EACH ROW
DECLARE
koszt number (10, 0);
BEGIN
    select koszt_utworzenia into koszt from RODZAJE_MAREK where jakosc_marki = :NEW.rodzaje_marek_jakosc_marki;
    update producent set FUNDUSZE = FUNDUSZE - koszt where ID_PRODUCENTA = :NEW.producent_id_producenta;
END;

/
ALTER TRIGGER "INZYNIERKA"."KOSZT_UTWORZENIA_MARKI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POTRACENIE_KOSZTOW_PRODUKCJI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."POTRACENIE_KOSZTOW_PRODUKCJI" 
AFTER INSERT ON PRODUKCJA
for each row
DECLARE
id_producenta number (3,0);
BEGIN
    select p.id_producenta into id_producenta from producent p, marka m where p.ID_PRODUCENTA = m.PRODUCENT_ID_PRODUCENTA AND m.ID_MARKI = :NEW.marka_id_marki;
    update producent set FUNDUSZE = FUNDUSZE - :new.koszt where ID_PRODUCENTA = id_producenta;
END;

/
ALTER TRIGGER "INZYNIERKA"."POTRACENIE_KOSZTOW_PRODUKCJI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPR_MOZLIWOSCI_PRODUKCJI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."SPR_MOZLIWOSCI_PRODUKCJI" 
BEFORE INSERT ON PRODUKCJA
for each row
DECLARE
fund number (10,0);
koszt_prod number (10, 0);
BEGIN
    --ustawienie kosztu i sprawdzenie czy producent ma fundusze
    select p.fundusze into fund from producent p, marka m where p.ID_PRODUCENTA = m.PRODUCENT_ID_PRODUCENTA AND m.ID_MARKI = :NEW.marka_id_marki;
    select r.KOSZT_PRODUKCJI_SZTUKI into koszt_prod from RODZAJE_MAREK r, marka m where r.jakosc_marki = m.rodzaje_marek_jakosc_marki AND m.ID_MARKI = :NEW.marka_id_marki;
    koszt_prod := koszt_prod * :new.ilosc;
    if fund < koszt_prod then
        raise_application_error(-20801, 'Niewystarczajce fundusze');
    end if;
    :new.koszt := koszt_prod;

    --dodanie numeru rundy
    select max(numer_rundy) into :new.licznik_rund_numer_rundy from licznik_rund;
END;

/
ALTER TRIGGER "INZYNIERKA"."SPR_MOZLIWOSCI_PRODUKCJI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UZUPELNIENIE_HISTORII_CEN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INZYNIERKA"."UZUPELNIENIE_HISTORII_CEN" 
AFTER INSERT OR UPDATE OF CENA_ZA_SZTUKE ON MARKA
FOR EACH ROW
DECLARE
nr_rundy number (5,0);
BEGIN
    select max(numer_rundy) into nr_rundy from licznik_rund;
    insert into HISTORIA_CEN values (:new.cena_za_sztuke, :new.id_marki, nr_rundy);
END;

/
ALTER TRIGGER "INZYNIERKA"."UZUPELNIENIE_HISTORII_CEN" ENABLE;
--------------------------------------------------------
--  DDL for Procedure GENERUJ_KONSUMENTOW
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."GENERUJ_KONSUMENTOW" 
IS
    liczba_kons NUMERIC(10);
BEGIN
    select liczba_konsumentow into liczba_kons from ustawienia_poczatkowe where numer_opcji = 1;
    FOR i IN 1 ..liczba_kons LOOP
    insert into konsument values (null, DBMS_RANDOM.value(100, 10000), DBMS_RANDOM.value(100, 10000), DBMS_RANDOM.value(1, 10), 
                       DBMS_RANDOM.value(1, 10), DBMS_RANDOM.value(1, 10), DBMS_RANDOM.value(1, 10), DBMS_RANDOM.value(0, 0.99));
  END LOOP;
END GENERUJ_KONSUMENTOW;

/
--------------------------------------------------------
--  DDL for Procedure ROZPOCZNIJ_GRE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."ROZPOCZNIJ_GRE" (wybrana_opcja NUMBER) AS
BEGIN
    --sprawdzenie czy jest w oparciu o co startowac nowa runde
        --na razie opcja 1 - dodac pole aktywnej opcji w ustaiwniach pocz
    declare
        aktywna_opcja number;
    BEGIN
        select count(numer_opcji) into aktywna_opcja from USTAWIENIA_POCZATKOWE where NUMER_OPCJI = wybrana_opcja;
        if aktywna_opcja <> 1 then
            raise_application_error(-20805, 'Wybrana opcja ustawien poczatkowych nie istnieje');
        end if;
    END;
    --czyszczenie zawartosci po poprzedniej grze
    WYCZYSC_TABELE;
    --restartowanie sekwencji
    ZRESTARTUJ_SEKWENCJE;
    --stworzenie uzytkownikow i dodanie ich do tabeli producentow
    --uzupelnienie tabel zawierajacych jakosc marki i koszty marketingu
END ROZPOCZNIJ_GRE;

/
--------------------------------------------------------
--  DDL for Procedure ROZPOCZNIJ_RUNDE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."ROZPOCZNIJ_RUNDE" AS
--procedura uruchamiana rozpoczyna nowa runde poprzez zwiekszenie licznika rund
BEGIN
  --realizacja dzialan marketingowych
  --zwiekszenie licznika rund - ! czy z sekwencja ma to sens
  insert into licznik_rund values (null);
  --realizacja zakupow klientow
  --koszty magazynowania na kolejna runde
END ROZPOCZNIJ_RUNDE;

/
--------------------------------------------------------
--  DDL for Procedure STWORZ_GRACZY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."STWORZ_GRACZY" (liczba_graczy number) authid current_user AS 
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER Gracz_1 IDENTIFIED BY symulator';
    FOR i IN 1..liczba_graczy
    LOOP
          --EXECUTE IMMEDIATE 'CREATE USER Gracz_' || i || 'IDENTIFIED BY symulator';
          null;
    END LOOP;
END STWORZ_GRACZY;

/
--------------------------------------------------------
--  DDL for Procedure WYCZYSC_TABELE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."WYCZYSC_TABELE" AS 
BEGIN
  --czyszczenie
    BEGIN
        EXECUTE IMMEDIATE 'TRUNCATE TABLE koszt_magazynowania';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE zakup_konsumenta';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE marketing';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE badania_rynku';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE historia_cen';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE magazynowanie';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE produkcja';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE sprzedaz';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE przywiazanie_do_marki';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE marka';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE rodzaje_marek';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE rodzaj_marketingu';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE licznik_rund';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE konsument';
        EXECUTE IMMEDIATE 'TRUNCATE TABLE producent';
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.put_line ('Czyszczenie tabel nie powiodlo sie');
    END;
END WYCZYSC_TABELE;

/
--------------------------------------------------------
--  DDL for Procedure ZRESTARTUJ_SEKWENCJE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "INZYNIERKA"."ZRESTARTUJ_SEKWENCJE" AS 
BEGIN
    --restartowanie sekwencji
    BEGIN
        --autoinkrementacja id konsumenta
        EXECUTE IMMEDIATE 'DROP SEQUENCE ID_KONSUMENTA_SEQ';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ID_KONSUMENTA_SEQ INCREMENT BY 1 START WITH 1';
        --autoinkrementacja licznika rund
        EXECUTE IMMEDIATE ' SEQUENCE LICZNIK_RUND_SEQ';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE LICZNIK_RUND_SEQ INCREMENT BY 1 START WITH 1';
        --autoinkrementacja id marki
        EXECUTE IMMEDIATE 'DROP SEQUENCE ID_MARKI_SEQ';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ID_MARKI_SEQ INCREMENT BY 1 START WITH 1';
        --autoinkrementacja id rodzaju marketingu
        EXECUTE IMMEDIATE 'DROP SEQUENCE ID_RODZ_MARKETINGU_SEQ';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ID_RODZ_MARKETINGU_SEQ INCREMENT BY 1 START WITH 1';
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.put_line ('Restartowanie sekwencji nie powiodlo sie.');
    END;
END ZRESTARTUJ_SEKWENCJE;

/
--------------------------------------------------------
--  Constraints for Table LICZNIK_RUND
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."LICZNIK_RUND" ADD CONSTRAINT "LICZNIK_RUND_PK" PRIMARY KEY ("NUMER_RUNDY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."LICZNIK_RUND" MODIFY ("NUMER_RUNDY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KONSUMENT
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."KONSUMENT" ADD CONSTRAINT "KONSUMENT_PK" PRIMARY KEY ("ID_KONSUMENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("PODATNOSC_NA_MARKETING" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("PRZYWIAZANIE_ZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("PRZYWIAZANIE_NIEZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("PRZYWIAZANIE_POZIOM_REZERWACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("PRZYWIAZANIE_POZIOM_ASPIRACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("JAKOSC_ZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("JAKOSC_NIEZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("JAKOSC_POZIOM_REZERWACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("JAKOSC_POZIOM_ASPIRACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("CENA_ZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("CENA_NIEZADOWOLENIE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("CENA_POZIOM_REZERWACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("CENA_POZIOM_ASPIRACJI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KONSUMENT" MODIFY ("ID_KONSUMENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAGAZYNOWANIE
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" ADD CONSTRAINT "MAGAZYNOWANIE_PK" PRIMARY KEY ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" MODIFY ("KOSZT" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" MODIFY ("ILOSC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KOSZT_MAGAZYNOWANIA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."KOSZT_MAGAZYNOWANIA" ADD CONSTRAINT "KOSZT_MAGAZYNOWANIA_PK" PRIMARY KEY ("NR_PRZEDZIALU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."KOSZT_MAGAZYNOWANIA" MODIFY ("KOSZT" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."KOSZT_MAGAZYNOWANIA" MODIFY ("NR_PRZEDZIALU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BADANIA_RYNKU
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" ADD CONSTRAINT "BADANIA_RYNKU_PK" PRIMARY KEY ("PRODUCENT_ID_PRODUCENTA", "LICZNIK_RUND_NUMER_RUNDY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" MODIFY ("DOKLADNOSC" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" MODIFY ("HORYZONT_CZASOWY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" MODIFY ("LICZBA_KLIENTOW" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" MODIFY ("PRODUCENT_ID_PRODUCENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USTAWIENIA_POCZATKOWE
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" ADD CONSTRAINT "USTAWIENIA_POCZATKOWE_PK" PRIMARY KEY ("NUMER_OPCJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("POCZATKOWE_FUNDUSZE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("LICZBA_RUND" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("CZAS_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("WARUNEK_ZAKONCZENIA_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("LICZBA_KONSUMENTOW" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."USTAWIENIA_POCZATKOWE" MODIFY ("NUMER_OPCJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RODZAJ_MARKETINGU
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."RODZAJ_MARKETINGU" ADD CONSTRAINT "RODZAJ_MARKETINGU_PK" PRIMARY KEY ("ID_RODZAJU_MARKETINGU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."RODZAJ_MARKETINGU" MODIFY ("KOSZTA_PER_KLIENT" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."RODZAJ_MARKETINGU" MODIFY ("KOSZT_STALY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."RODZAJ_MARKETINGU" MODIFY ("ID_RODZAJU_MARKETINGU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPRZEDAZ
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" ADD CONSTRAINT "SPRZEDAZ_PK" PRIMARY KEY ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" MODIFY ("PRZYCHOD" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" MODIFY ("ILOSC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARKA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MARKA" ADD CONSTRAINT "MARKA_NAZWA_UN" UNIQUE ("NAZWA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKA" ADD CONSTRAINT "MARKA_PK" PRIMARY KEY ("ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKA" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKA" MODIFY ("RODZAJE_MAREK_JAKOSC_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKA" MODIFY ("PRODUCENT_ID_PRODUCENTA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKA" MODIFY ("CENA_ZA_SZTUKE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKA" MODIFY ("ID_MARKI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRZYWIAZANIE_DO_MARKI
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" ADD CONSTRAINT "PRZYWIAZANIE_DO_MARKI_PK" PRIMARY KEY ("KONSUMENT_ID_KONSUMENTA", "MARKA_ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" MODIFY ("WSPOLCZYNNIK_PRZYWIAZANIA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" MODIFY ("KONSUMENT_ID_KONSUMENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MARKETING
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MARKETING" ADD CONSTRAINT "MARKETING_PK" PRIMARY KEY ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKETING" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKETING" MODIFY ("KOSZT" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKETING" MODIFY ("LICZBA_KLIENTOW" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKETING" MODIFY ("RODZ_MARKET_ID_RODZ_MARKETINGU" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."MARKETING" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUKCJA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."PRODUKCJA" ADD CONSTRAINT "PRODUKCJA_PK" PRIMARY KEY ("LICZNIK_RUND_NUMER_RUNDY", "MARKA_ID_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."PRODUKCJA" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUKCJA" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUKCJA" MODIFY ("KOSZT" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUKCJA" MODIFY ("ILOSC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIA_CEN
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" ADD CONSTRAINT "HISTORIA_CEN_PK" PRIMARY KEY ("MARKA_ID_MARKI", "LICZNIK_RUND_NUMER_RUNDY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" MODIFY ("CENA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RODZAJE_MAREK
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."RODZAJE_MAREK" ADD CONSTRAINT "RODZAJE_MAREK_PK" PRIMARY KEY ("JAKOSC_MARKI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."RODZAJE_MAREK" MODIFY ("KOSZT_PRODUKCJI_SZTUKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."RODZAJE_MAREK" MODIFY ("KOSZT_UTWORZENIA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."RODZAJE_MAREK" MODIFY ("JAKOSC_MARKI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZAKUP_KONSUMENTA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" ADD CONSTRAINT "ZAKUP_KONSUMENTA_PK" PRIMARY KEY ("KONSUMENT_ID_KONSUMENTA", "LICZNIK_RUND_NUMER_RUNDY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" MODIFY ("MARKA_ID_MARKI" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" MODIFY ("KONSUMENT_ID_KONSUMENTA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" MODIFY ("LICZNIK_RUND_NUMER_RUNDY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCENT
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."PRODUCENT" MODIFY ("FUNDUSZE" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUCENT" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUCENT" MODIFY ("ID_PRODUCENTA" NOT NULL ENABLE);
  ALTER TABLE "INZYNIERKA"."PRODUCENT" ADD CONSTRAINT "PRODUCENT_PK" PRIMARY KEY ("ID_PRODUCENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INZYNIERKA"."PRODUCENT" ADD CHECK ( czy_spasowal IN (
        'n',
        't'
    ) ) ENABLE;
  ALTER TABLE "INZYNIERKA"."PRODUCENT" MODIFY ("CZY_SPASOWAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BADANIA_RYNKU
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" ADD CONSTRAINT "BADANIA_RYNKU_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."BADANIA_RYNKU" ADD CONSTRAINT "BADANIA_RYNKU_PRODUCENT_FK" FOREIGN KEY ("PRODUCENT_ID_PRODUCENTA")
	  REFERENCES "INZYNIERKA"."PRODUCENT" ("ID_PRODUCENTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIA_CEN
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" ADD CONSTRAINT "HISTORIA_CEN_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."HISTORIA_CEN" ADD CONSTRAINT "HISTORIA_CEN_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAGAZYNOWANIE
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" ADD CONSTRAINT "MAGAZYNOWANIE_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."MAGAZYNOWANIE" ADD CONSTRAINT "MAGAZYNOWANIE_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARKA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MARKA" ADD CONSTRAINT "MARKA_PRODUCENT_FK" FOREIGN KEY ("PRODUCENT_ID_PRODUCENTA")
	  REFERENCES "INZYNIERKA"."PRODUCENT" ("ID_PRODUCENTA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKA" ADD CONSTRAINT "MARKA_RODZAJE_MAREK_FK" FOREIGN KEY ("RODZAJE_MAREK_JAKOSC_MARKI")
	  REFERENCES "INZYNIERKA"."RODZAJE_MAREK" ("JAKOSC_MARKI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MARKETING
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."MARKETING" ADD CONSTRAINT "MARKETING_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKETING" ADD CONSTRAINT "MARKETING_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."MARKETING" ADD CONSTRAINT "MARKETING_RODZAJ_MARKETINGU_FK" FOREIGN KEY ("RODZ_MARKET_ID_RODZ_MARKETINGU")
	  REFERENCES "INZYNIERKA"."RODZAJ_MARKETINGU" ("ID_RODZAJU_MARKETINGU") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUKCJA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."PRODUKCJA" ADD CONSTRAINT "PRODUKCJA_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."PRODUKCJA" ADD CONSTRAINT "PRODUKCJA_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRZYWIAZANIE_DO_MARKI
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" ADD CONSTRAINT "PRZYWIAZANIE_DO_MARKI_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."PRZYWIAZANIE_DO_MARKI" ADD CONSTRAINT "PRZYW_DO_MARKI_KONSUMENT_FK" FOREIGN KEY ("KONSUMENT_ID_KONSUMENTA")
	  REFERENCES "INZYNIERKA"."KONSUMENT" ("ID_KONSUMENTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPRZEDAZ
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" ADD CONSTRAINT "SPRZEDAZ_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."SPRZEDAZ" ADD CONSTRAINT "SPRZEDAZ_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZAKUP_KONSUMENTA
--------------------------------------------------------

  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" ADD CONSTRAINT "ZAKUP_KONSUMENTA_KONSUMENT_FK" FOREIGN KEY ("KONSUMENT_ID_KONSUMENTA")
	  REFERENCES "INZYNIERKA"."KONSUMENT" ("ID_KONSUMENTA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" ADD CONSTRAINT "ZAKUP_KONSUMENTA_MARKA_FK" FOREIGN KEY ("MARKA_ID_MARKI")
	  REFERENCES "INZYNIERKA"."MARKA" ("ID_MARKI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "INZYNIERKA"."ZAKUP_KONSUMENTA" ADD CONSTRAINT "ZAKUP_KONSUM_LICZNIK_RUND_FK" FOREIGN KEY ("LICZNIK_RUND_NUMER_RUNDY")
	  REFERENCES "INZYNIERKA"."LICZNIK_RUND" ("NUMER_RUNDY") ON DELETE CASCADE ENABLE;
