DROP SEQUENCE numer_rundy_autoinc;
CREATE SEQUENCE numer_rundy_autoinc INCREMENT BY 1 START WITH 1;

BEGIN
  DBMS_SCHEDULER.DROP_JOB(JOB_NAME => 'ROZPOCZNIJ_NOWA_RUNDE');
END;

BEGIN
DBMS_SCHEDULER.CREATE_JOB (
    JOB_NAME        => 'ROZPOCZNIJ_NOWA_RUNDE',
    JOB_TYPE        => 'STORED_PROCEDURE',
    JOB_ACTION      => 'INZYNIERKA.ROZPOCZNIJ_RUNDE',
    START_DATE      => SYSTIMESTAMP,
    REPEAT_INTERVAL => 'FREQ=DAILY;INTERVAL=2;BYHOUR=1;BYMINUTE=0',
    END_DATE        => NULL,
    ENABLED         => TRUE,
    COMMENTS        => 'Job rozpoczyna nowa runde');
END;