--sekwencje
--autoinkrementacja id badania rynku
CREATE SEQUENCE ID_BADANIA_RYNKU_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja id grupy konsumentow
CREATE SEQUENCE ID_GRUPY_KONSUMENTOW_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja marketingu
CREATE SEQUENCE ID_MARKETINGU_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja id marki
CREATE SEQUENCE ID_MARKI_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja id produkcji
CREATE SEQUENCE ID_PRODUKCJI_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja id ustawien poczatkowych
CREATE SEQUENCE NR_ZESTAWU_USTAWIEN_POCZ_SEQ INCREMENT BY 1 START WITH 1;
--autoinkrementacja id producenta
CREATE SEQUENCE ID_PRODUCENTA_SEQ INCREMENT BY 1 START WITH 1;