--sekwencje

--autoinkrementacja licznika rund
DROP SEQUENCE LICZNIK_RUND_SEQ;
CREATE SEQUENCE LICZNIK_RUND_SEQ INCREMENT BY 1 START WITH 1 Order;

--autoinkrementacja id marki
DROP SEQUENCE ID_MARKI_SEQ;
CREATE SEQUENCE ID_MARKI_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id produkcji
DROP SEQUENCE ID_PRODUKCJI_SEQ;
CREATE SEQUENCE ID_PRODUKCJI_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id ustawien poczatkowych
DROP SEQUENCE NR_OPCJI_USTAWIEN_POCZ_SEQ;
CREATE SEQUENCE NR_OPCJI_USTAWIEN_POCZ_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id rodzaju marketingu
DROP SEQUENCE ID_RODZAJU_MARKET_SEQ;
CREATE SEQUENCE ID_RODZAJU_MARKET_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id badania rynku
DROP SEQUENCE ID_BADANIA_RYNKU_SEQ;
CREATE SEQUENCE ID_BADANIA_RYNKU_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id producenta
DROP SEQUENCE ID_PRODUCENTA_SEQ;
CREATE SEQUENCE ID_PRODUCENTA_SEQ INCREMENT BY 1 START WITH 1;