--sekwencje
--autoinkrementacja id konsumenta
DROP SEQUENCE ID_KONSUMENTA_SEQ;
CREATE SEQUENCE ID_KONSUMENTA_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id producenta
DROP SEQUENCE ID_PRODUCENTA_SEQ;
CREATE SEQUENCE ID_PRODUCENTA_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja licznika rund
DROP SEQUENCE LICZNIK_RUND_SEQ;
CREATE SEQUENCE LICZNIK_RUND_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id marki
DROP SEQUENCE ID_MARKI_SEQ;
CREATE SEQUENCE ID_MARKI_SEQ INCREMENT BY 1 START WITH 1;

--autoinkrementacja id rodzaju marketingu
DROP SEQUENCE ID_RODZ_MARKETINGU_SEQ;
CREATE SEQUENCE ID_RODZ_MARKETINGU_SEQ INCREMENT BY 1 START WITH 1;
